spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # Oracle 디비를 사용할 때 추가가 필요 디비에 맞춰서 쿼리를 자동으로 생성해줌.
        # dialect: org.hibernate.dialect.Oracle10gDialect
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace